-- Generated by nwg-displays on 2026-06-08 at 00:19:52. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2880x1920@120.0",
    position = "2007x1440",
    scale = 2.0
})

hl.monitor({
    output = "DP-2",
    mode = "2560x1440@59.95",
    position = "1440x0",
    scale = 1.0
})
